
r = [ 0 0; ...
      0 1; ...
      1 1; ...
      1 3; ...
      2 3 ];

edges = [ 1 2; ...
          2 5; ...
          2 3; ...
          1 3; ...
          1 4; ...
          1 5 ];

for ni=1:2
    for nj=1:2
        v  = integ_edge_uu( r, edges, ni, nj );
        vq = v*0;
        for e=1:size(edges,1);
            r1 = r( edges(e, 1), : );
            r2 = r( edges(e, 2), : );
            vq(e) = iquad_edge_uu( r1, r2, ni, nj );
        end
        assert( norm(v-vq)<1.0e-10, "test_integ_edge_uu failed" )
    end
end
